[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs>=0.5",
  "hatchling>=1.32.4",
]

[project]
name = "tox-gh"
description = "Seamless integration of tox into GitHub Actions."
readme = "README.md"
keywords = [
  "environments",
  "isolated",
  "testing",
  "virtual",
]
license = "MIT"
maintainers = [
  { name = "Bernát Gábor", email = "gaborjbernat@gmail.com" },
]
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries",
  "Topic :: System",
]
dynamic = [
  "version",
]
dependencies = [
  "tox>=4.64.7",
  "typing-extensions>=4.16; python_version<'3.12'",
]
urls.Documentation = "https://github.com/tox-dev/tox-gh#tox-gh"
urls.Homepage = "https://github.com/tox-dev/tox-gh"
urls.Source = "https://github.com/tox-dev/tox-gh"
urls.Tracker = "https://github.com/tox-dev/tox-gh/issues"
entry-points.tox.tox-gh = "tox_gh.plugin"

[dependency-groups]
test = [
  "covdefaults>=2.3",
  "devpi-process>=1.2",
  "diff-cover>=10.6",
  "pytest>=9.1.1",
  "pytest-cov>=7.1",
  "pytest-mock>=3.16",
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/tox_gh/version.py"
build.targets.sdist.include = [
  "/src",
  "/tests",
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
format.preview = true
format.docstring-code-line-length = 100
format.docstring-code-format = true
lint.select = [
  "ALL",
]
lint.ignore = [
  "CPY",                                       # No copyright statements
  "DOC",                                       # not supported
  "escape-sequence-in-docstring",              # Use `r"""` if any backslashes in a docstring
  "hardcoded-bind-all-interfaces",             # Possible binding to all interface
  "incorrect-blank-line-before-class",         # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible
  "missing-blank-line-after-summary",          # 1 blank line required between summary line and description
  "missing-trailing-comma",                    # Conflict with formatter
  "multi-line-summary-first-line",             # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible
  "non-imperative-mood",                       # First line of docstring should be in imperative mood
  "root-logger-call",                          # call on root logger
  "single-line-implicit-string-concatenation", # Conflict with formatter
]
lint.per-file-ignores."tests/**/*.py" = [
  "assert",                               # asserts allowed in tests
  "D",                                    # don't care about documentation in tests
  "FBT",                                  # don't care about booleans as positional arguments in tests
  "implicit-namespace-package",           # no implicit namespace
  "magic-value-comparison",               # Magic value used in comparison, consider replacing with a constant variable
  "pytest-fixture-autouse",               # shared setup fixtures are meant to apply to every test
  "subprocess-without-shell-equals-true", # `subprocess` call: check for execution of untrusted input
]
lint.isort = { known-first-party = [
  "tox_gh",
  "tests",
], required-imports = [
  "from __future__ import annotations",
] }
lint.preview = true

[tool.codespell]
builtin = "clear,usage,en-GB_to_en-US"
write-changes = true
count = true

[tool.pyproject-fmt]
max_supported_python = "3.15"

[tool.ty]
environment.python-version = "3.15"

[tool.coverage]
run.parallel = true
run.plugins = [
  "covdefaults",
]
paths.other = [
  ".",
  "*/tox_gh",
  "*\\tox_gh",
]
paths.source = [
  "src",
  ".tox/*/lib/*/site-packages",
  ".tox\\*\\Lib\\site-packages",
  "**/src",
  "**\\src",
]
report.fail_under = 96
html.show_contexts = true
html.skip_covered = false
